# Generated by Django 5.1.4 on 2025-02-04 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalVisitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='additional_visitor_image/')),
            ],
            options={
                'db_table': 'additional_visitor',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('next', 'Next')], default='pending', max_length=20)),
                ('company_name', models.CharField(default='NA', max_length=100)),
                ('company_address', models.CharField(default='NA', max_length=100)),
                ('purpose_of_visit', models.CharField(default='Na', max_length=100)),
                ('visitor_img', models.ImageField(blank=True, upload_to='visitor_img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
