# Generated by Django 5.1.5 on 2025-01-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='AdditionalVisitor',
        ),
    ]
