# Generated by Django 5.1.5 on 2025-01-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_participant_additionalvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalvisitor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='additional_visitor_image/'),
        ),
        migrations.AlterField(
            model_name='additionalvisitor',
            name='participants',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='additional_visitor', to='appointment.appointment'),
        ),
    ]
