# Generated by Django 5.1.5 on 2025-01-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_additionalvisitor_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalvisitor',
            name='img',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='visitor_img',
        ),
    ]
