# Generated by Django 5.1.5 on 2025-01-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_additionalvisitor_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalvisitor',
            name='img',
            field=models.ImageField(blank=True, upload_to='additional_visitor_image/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='visitor_img',
            field=models.ImageField(blank=True, upload_to='visitor_img/'),
        ),
    ]
