# Generated by Django 5.1.5 on 2025-01-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_delete_participant_appointment_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partici',
            new_name='Participant',
        ),
    ]
