# Generated by Django 5.1.5 on 2025-01-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_rename_partici_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='participants',
        ),
    ]
