# Generated by Django 5.1.5 on 2025-01-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_participant_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participants',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='appointment.appointment'),
        ),
    ]
