# Generated by Django 5.1.5 on 2025-01-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_participant_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
