# Generated by Django 5.1.5 on 2025-01-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('next', 'Next')], default='pending', max_length=20),
        ),
    ]
