# Generated by Django 5.1.5 on 2025-01-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_participant_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='client',
        ),
    ]
