# Generated by Django 5.1.5 on 2025-01-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_gm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gm', 'GM'), ('pa', 'PA')], default='pa', max_length=10),
        ),
    ]
