# Generated by Django 5.1.5 on 2025-01-29 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gm',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'gm'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
