# Generated by Django 5.1.5 on 2025-01-29 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshocket', '0002_callnotification_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callnotification',
            name='id',
        ),
        migrations.AddField(
            model_name='callnotification',
            name='call_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
